### PR TITLE
0.12 updates

### PR DESCRIPTION
**Pull request by nsaunders**
* Upgraded library versions
* Updates for various API changes (effects, generics, rows, spec)
* Updated Travis configuration

_Note that this is an early pull request awaiting [purescript-trout#8](https://github.com/owickstrom/purescript-trout/pull/8) and [hyper#64](https://github.com/owickstrom/hyper/pull/64)._

### CODE REVIEW

**Comment by nsaunders** [comment]
@owickstrom, with the [hyper](https://github.com/owickstrom/hyper) dependency upgraded to v0.9.0, I think this PR is now ready for your review.

**Review by owickstrom — APPROVED** [review]
Looks good!

**Comment by nsaunders** [comment]
Wonderful, thanks for your review @owickstrin. Unfortunately I think I am lacking the option to merge this one myself, so if you would be so kind... Thanks in advance!

**Comment by owickstrom** [comment]
Of course! Adding the authorization you need...

**Pull request merged**
