### PR TITLE
Bower version resolutions

### PR DESCRIPTION
**Pull request by owickstrom**
Noticed master wasn't compiling anymore. Not sure if these resolutions make sense. @nicholassaunders any input on the conflicting versions?

### CODE REVIEW

**Comment by nsaunders** [comment]
In what environment did you observe the compilation error? I’ve had to blow away my bower_components directory (which also means the output directory) at times for Bower not to prompt about version conflicts. But if the environment was clean then I definitely probably made a mistake somewhere... I will certainly look into it when I get back to my computer. Thanks @owickstrom.

**Comment by nsaunders** [comment]
OK, I think the issue you encountered @owickstrom was the result of upstream version conflicts. If owickstrom/hyper#76 seems reasonable to you, then we could probably resolve this by releasing a new 0.9.1 version of Hyper, with no changes required here. What do you think?

**Comment by owickstrom** [comment]
@nicholassaunders That sounds good. :+1:

**Comment by owickstrom** [comment]
The error showed up when I merged your PR, in the Travis CI build. Reproduced it locally.

**Comment by nsaunders** [comment]
A quick update... After removing the explicit ```purescript-argonaut-*``` dependencies from Hyper and cutting a new release, this issue persists (although I still think this was probably a good change). However, I determined that running this in a clean directory results in a version conflict:

```
bower install purescript-argonaut@^5.0.0 purescript-argonaut-generic
```

So I think we probably still need the resolutions for now. I actually found that the project builds (including examples) and all tests pass given these resolutions (later versions):

```
+  },
+  "resolutions": {
+    "purescript-argonaut-core": "^5.0.0",
+    "purescript-record": "^2.0.0",
+    "purescript-argonaut-codecs": "^6.0.2",
+    "purescript-foreign-object": "^2.0.0",
+    "purescript-typelevel-prelude": "^4.0.0"
```

@owickstrom, would you want to update your resolutions, or should we merge as-is?

**Pull request merged**
